### ISSUE TITLE
Split `honey_badger` into smaller modules.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#121]
The decryption part involves many lines of code in `honey_badger.rs`. I wonder whether this could be split out into a private submodule. We could write a kind of collection in which you can put the ciphertext and decryption shares and which would automatically return the decrypted item as soon as it has enough information. If both steps (Subset and Decryption) are separate modules, `honey_badger.rs` should be very simple and easy to read.

**Comment by afck** [comment]
In addition to separating the Subset and Decryption step, we could also factor out a single epoch. So:

`HoneyBadger` would simply dispatch and filter messages by epoch, and run a `HoneyBadgerEpoch` instance for each of them. A `HoneyBadgerEpoch` would first run one `CommonSubset`, and then one `Decryption` instance.

**Comment by c0gent** [comment]
I think this is a great idea. Splitting things up creates a bit more work but is helpful for keeping concerns separate and making drawing clearer boundaries. I sometimes separate things based on shared import grouping. This occasionally highlights structural patterns that I hadn't otherwise considered. Obviously there are limits to all of this and following the principles of laziness tends to be a good guide!
