### ISSUE TITLE
Use error-chain.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#17]
It provides a macro to implement the `Error` trait and error conversions.

(There are lots of error handling crates, but error-chain is what e.g. ethabi, ethcore and poa-bridge also use.)

**Comment by DrPeterVanNostrand** [comment]
For the moment, `error-chain` can't be used by `hbbft` because we depend on`reed_solomon_erasure::Error` which doesn't implement the `std::error::Error` trait, all error types that get chained together by `error-chain` must implement `std::error::Error`.

I'm going to file an Issue with `reed_solomon_erasure` requesting the feature. So at least for now, hbbft is stuck with error enums. If the issue isn't picked up, I might be able to submit a PR implementing std Error.

**Comment by afck** [comment]
But an error variant can contain any kind of parameter, can't it? So due to that limitation the `ReedSolomon(reed_solomon_erasure::Error)` variant wouldn't be in `foreign_links`, but it could still live in the `errors` section for now?

(That said, I agree that not implementing the `Error` trait is an omission that should be fixed in the `reed_solomon_erasure`!)
