### ISSUE TITLE
Remove synchrony in HB Epoch State

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#282]
At the moment, `EpochState` expects decryption shares only for "accepted proposers", that is, nodes found in the output of `Subset`. If the order of messages changes within the same epoch, early decryption shares are discarded with a fault report. "Accepted proposers" aren't really necessary and removing them would allow to reorder messages without breaking HB output.

**Comment by afck** [comment]
Yes, it's definitely meant to handle them in any order:

* [_If_ we already know the accepted proposers](https://github.com/poanetwork/hbbft/blob/b3e858a07946009a12d78461457f28424b1aecc8/src/honey_badger/epoch_state.rs#L238), we discard incoming shares for rejected ones, otherwise we accept all shares.

* [Once we learn about the accepted proposers](https://github.com/poanetwork/hbbft/blob/b3e858a07946009a12d78461457f28424b1aecc8/src/honey_badger/epoch_state.rs#L316), we discard those shares for rejected ones which we had received earlier.

So you're saying the first point has a bug, and we reject early shares where we shouldn't? Is there an easy way to reproduce that?

**Comment by vkomenda** [comment]
I was triggering the second condition with the sender queue. When `accepted_proposers` is a strict subset of all validators and there is an ongoing, incomplete decryption state of a validator which is not an accepted proposer, this condition outputs a fault because that validator is a `faulty share`.

**Comment by afck** [comment]
But for the proposal of a validator that was not accepted, nobody should ever even send a decryption share. So maybe the bug occurred earlier, and the outputs of `Subset` didn't even agree among the nodes?
In general, if a node sends you a decryption share for a proposal whose proposer gets rejected by `Subset` (in any order), that node is faulty.

**Comment by vkomenda** [comment]
This bug turned out slightly different. Subset may output `Done` before getting outputs from all broadcast instances. Since #233.
