### ISSUE TITLE
Split up `FaultKind`.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#285]
`FaultKind`s should form a hierarchy similar (and parallel) to errors, and live in the respective modules.

Let's create a `FaultKind` enum for each algorithm, with `SubAlgorithm(sub_algorithm::FaultKind)` variants where needed (like currently with `AckMessageFault`), and possibly with corresponding `From` impls. I think even `Fault` and `FaultLog` should be generic in the fault kind, so that if you're using `BinaryAgreement`, the compiler doesn't force you to consider `HoneyBadger` faults.

They should all implement `Display`, and print an explanation (basically what's currently the doc comment). Maybe we should derive `Fail` to make this easier?

**Comment by alyjak** [comment]
Proposed Design:

1. Instead of including every module's `FaultKind` enumerations within `fault_log`, create a generic
   `ByzantineFaultKind` enumeration used to wrap module specific faults. `ByzantineFaultKind` enums
   wrap structs which implement `Fail`.
2.  Implement `failure::Fault.cause()` and `failure::Fault.context()` for `Fault` and `ByzantineFaultKind`.
3. Incrementally replace `fault_log::FaultKind` with `ByzantineFaultKind`. Add module tests during
    each replacement such that each module-specific fault trigger is tested.

**Comment by afck** [comment]
Actually, do we need a generic `ByzantineFaultKind`? Isn't it enough if every algorithm has its `FaultKind` enum (some variants of which possibly wrap other modules' `FaultKind`s), and we make `Step` generic in the `FaultKind`?

**Comment by alyjak** [comment]
True, I was thinking the generic would be useful for binning faults further up the stack. After our conversation on Gitter the other day I understand that is not likely necessary as any issued fault is sufficient reason to consider the sender faulted. Consider generic `ByzantineFaultKind` gone!
