### ISSUE TITLE
Fix issues that don't allow message reordering

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#300]
A failing test case is available in a branch: https://github.com/poanetwork/hbbft/tree/vk-reordering-adversary. This test is different from the one in master only in that it picks a random message from the network queue instead of picking the first message. That suffices to break it.

**Comment by afck** [comment]
It seems to always fail with `SubsetHandlingStrategy::Incremental`, but also sometimes with `SubsetHandlingStrategy::AllAtEnd`.

Note that proptest always reduced it to network size 1 for me, which doesn't make sense for this test. I think it was because of #303.

**Comment by afck** [comment]
OK, I found _an_ issue, which seems to make things fail later, at least…

```diff
diff --git a/src/subset.rs b/src/subset.rs
index c431d55..abe0934 100644
--- a/src/subset.rs
+++ b/src/subset.rs
@@ -247,7 +247,9 @@ impl<N: NodeIdT + Rand> Subset<N> {
             error!("Duplicate insert in broadcast_results: {:?}", inval)
         }
         let set_binary_agreement_input = |ba: &mut BinaryAgreement<N>| ba.handle_input(true);
-        Ok(step.join(self.process_binary_agreement(proposer_id, set_binary_agreement_input)?))
+        Ok(step
+            .join(self.process_binary_agreement(proposer_id, set_binary_agreement_input)?)
+            .with_output(self.try_binary_agreement_completion()))
     }
```

The problem was that if we received the `BinaryAgreement` result _first_, then when receiving the `Broadcast` output, `process_binary_agreement` wouldn't call `try_binary_agreement_completion` anymore, and never output.

With this, the tests fail later for me: they successfully remove the node, and vote for adding, but the added node never receives the next batch after that.

**Comment by vkomenda** [comment]
Excellent! The DHB tests fail less often with this now. But there looks to be a problem with the added node as you said, and `drop_and_readd` catches it.

**Comment by afck** [comment]
I think I found the (an?) other problem: #305
With that, the test passed 20 times for me.

**Comment by vkomenda** [comment]
I believe this is fixed in master. If another bug comes up, we can reopen the issue.
