### ISSUE TITLE
Subset: Drop Broadcast as soon as BinaryAgreement outputs false.

### ISSUE THREAD

**Issue by afck** [poanetwork/hbbft#313]
As soon as a `BinaryAgreement` instance in `Subset` has output `false`, all messages in the corresponding `Broadcast` instance are a waste of bandwidth.

**Comment by vkomenda** [comment]
PR #315 adds [more detail](https://github.com/poanetwork/hbbft/blob/48377286f23abe436bc4347d8411ecd05ffab758/src/subset.rs#L256) on this issue. [This error](https://github.com/poanetwork/hbbft/blob/ad35ebafd55b60e25b86fd1f86bf0e871db750c8/src/subset.rs#L256) can be avoided if the broadcast instance is replaced with its result as soon as it is output. @afck suggests merging `Subset::broadcast_instances` and `Subset::broadcast_results` so that you cannot have both at the same time.
