### ISSUE TITLE
Dynamic Honey Badger with one validator doesn't output a Change batch

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/hbbft#358]
As it stands now, `DynamicHoneyBadger::vote_for` doesn't output a batch with the validator set change immediately. Consequently, the `DynamicHoneyBadger` instance in question never changes the set of validators.

`vote_for` has to check if our instance is the only one in the network and output a batch with the change right away.

**Comment by afck** [comment]
As discussed, I think this change would make the DHB API even weirder.
That said, it is _already_ pretty weird and it would be great to come up with something more sane and understandable.

At the moment, `vote_for` just multicasts a message, so that all the participants/validators (including myself) will try to include my vote in the next batch—whenever that may be! It will never cause a batch to be output.

The reason is that DHB has no notion of "transactions"; it just collects _one_ "contribution" from each participant and the guarantee is that each batch contains at least _N - f_ contributions (often _N_). While that may be an unintuitive behavior, I think adding exceptions to it would make it even less intuitive. And to output a zero-contribution batch on `vote_for` in the case of a single participant sounds like a complicated and arbitrary exception.

Note that in QHB, where there are transactions and pending votes are taken into account when deciding whether to propose a contribution (possibly an empty one—which doesn't make sense for DHB), the behavior is already different: QHB should indeed output a batch on `vote_for` with a single participant. (If not, that's a bug.)

I agree that seems inconsistent, but I think it's better if DHB and QHB behave differently than if DHB behaves inconsistently by itself.

**Comment by vkomenda** [comment]
I agree that the API should be kept consistent. Proposing contributions solves the problem.
